{% set version = "1.5.0-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tmle
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tmle_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tmle/tmle_{{ version }}.tar.gz
  sha256: 9fc1f7432a40d8911393701ca33e2ad64356c3bd12128f01dd216399b16e3d93

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-superlearner >=2.0
    - r-glmnet
  run:
    - r-base
    - r-superlearner >=2.0
    - r-glmnet

test:
  commands:
    - $R -e "library('tmle')"           # [not win]
    - "\"%R%\" -e \"library('tmle')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tmle
  license: BSD_3_clause | GPL-2
  summary: Targeted maximum likelihood estimation of point treatment effects (Targeted Maximum Likelihood Learning, The International Journal of Biostatistics, 2(1), 2006.  This version automatically estimates the additive treatment effect among the treated (ATT) and among the controls (ATC).  The tmle() function calculates
    the adjusted marginal difference in mean outcome associated with a binary point treatment, for continuous or binary outcomes.  Relative risk and odds ratio estimates are also reported for binary outcomes. Missingness in the outcome is allowed, but not in treatment assignment or baseline covariate values.  The population
    mean is calculated when there is missingness, and no variation in the treatment assignment. The tmleMSM() function estimates the parameters of a marginal structural model for a binary point treatment effect. Effect estimation stratified by a binary mediating variable is also available. An ID argument can be used to identify
    repeated measures. Default settings call 'SuperLearner' to estimate the Q and g portions of the likelihood, unless values or a user-supplied regression function are passed in as arguments.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tmle
# Version: 1.4.0.1
# Date: 2019-10-15
# Title: Targeted Maximum Likelihood Estimation
# Authors@R: c(person("Susan", "Gruber", role = c("aut", "cre"), email = "sgruber@cal.berkeley.edu"), person("Mark", "van der Laan", role = "aut", email = "laan@berkeley.edu"), person("Chris", "Kennedy", role = "ctr", email = "ck37@berkeley.edu"))
# Author: Susan Gruber [aut, cre], Mark van der Laan [aut], Chris Kennedy [ctr]
# Maintainer: Susan Gruber <sgruber@cal.berkeley.edu>
# Copyright: Copyright 2012. The Regents of the University of California (Regents). All Rights Reserved.
# Depends: glmnet, SuperLearner (>= 2.0)
# Suggests: dbarts (>= 0.9-12), gam (>= 1.15)
# Description: Targeted maximum likelihood estimation of point treatment effects (Targeted Maximum Likelihood Learning, The International Journal of Biostatistics, 2(1), 2006.  This version automatically estimates the additive treatment effect among the treated (ATT) and among the controls (ATC).  The tmle() function calculates the adjusted marginal difference in mean outcome associated with a binary point treatment, for continuous or binary outcomes.  Relative risk and odds ratio estimates are also reported for binary outcomes. Missingness in the outcome is allowed, but not in treatment assignment or baseline covariate values.  The population mean is calculated when there is missingness, and no variation in the treatment assignment. The tmleMSM() function estimates the parameters of a marginal structural model for a binary point treatment effect. Effect estimation stratified by a binary mediating variable is also available. An ID argument can be used to identify repeated measures. Default settings call 'SuperLearner' to estimate the Q and g portions of the likelihood, unless values or a user-supplied regression function are passed in as arguments.
# License: BSD_3_clause + file LICENSE | GPL-2
# URL: https://CRAN.R-project.org/package=tmle
# NeedsCompilation: no
# Packaged: 2019-10-14 14:30:11 UTC; Susan
# Repository: CRAN
# Date/Publication: 2019-10-15 15:40:02 UTC
