appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: EKae9T8huJwB4xYsXmZyt8JcJFdHGtCV/2nl7HbhCcSfYFZxqhVUhBaCHzcrSny7EjBo0rz4KYyUV7LNCA+5gMNdbSYf0EguNPft6n/fjs/s7KAoa/Q125REm6x0lnYGYs70o+wcX/CiZxQvMJAColiTPMxaOkvcYpjMIjSkJURQd9G81NwbEkGK8k982E+dbo+ghEyFB3/W4TnuE86ZFFu3ptT43mqu/zGq+1JwVcFEkX0BcuJfZq0rijT7XT3o3g+UHUzojW5YGdxlsl4xcDUE8CUKiR8mBVuIbAIjEug6yT0yp8ZCMtjBcZlb5TVOJWvXPoREk/q2JvS3O4SFZuJec7+JCdXWbzIfYFNGobp3JFEV47hhMzVSHrtA56C7MB1Qij8tTieaF4eZYYtR+Wo3i0b/PY8zrKu6VSztdjaGtrPsyFtV3iB03MVCi5BnjSoXyxDxKal352KiO4I8dKTV1FdI/I7Nq3DVUWqqCG/SQ2BsY8fQcng7OY6E0d6zKa/5bD5QT/3iXQZ9sgMRXElU9svkuqZX65IrTiZ0Z63pRWRJHuiaw7F4Q7G64Bub2szDk4XyUHWblPTxCmPiZycVOUHFVzMihN8SIEjvvXb9bS6CxsmeeEw5zVpX2ao1dCoUMFkYVi0E4RY1djj1xMmmgQGOUrCVlaF/hEn1BHQ=}
